# Generated by Django 3.0.3 on 2020-02-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'managed': False},
        ),
    ]
